lazyload:
  enable: true
  js: https://gcore.jsdelivr.net/npm/vanilla-lazyload@17.3.1/dist/lazyload.min.js
  transition: blur # blur, fade

loading:
  loading: 正在加载...
  error: 加载失败！

style:
  gradient:
    start: ''
    search: ''
  border-radius:
    card: 12px
    block: 12px
    bar: 6px
    image: 6px
  font-family:
    body: '"Noto Serif", serif'

copycode:
  enable: false
  js: /js/plugins/copycode.js
  default_text: '复制代码'
  success_text: '复制成功'

link:
  underline: true

content: |
  - 本站使用 [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) 主题创建。
  - 本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。
